[versions]
java = "21"
springBoot = "3.4.1"
springDependencyManagement = "1.1.7"
kotlin = "1.9.25"
lombok = "1.18.36"  

[libraries]
# 웹 어플리케이션 및 API
spring-boot-starter-web = { group = "org.springframework.boot", name = "spring-boot-starter-web", version.ref = "springBoot" }

# 테스트 도구
spring-boot-starter-test = { group = "org.springframework.boot", name = "spring-boot-starter-test", version.ref = "springBoot" }

# 생산성 도구
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }

# 플러그인 구현채
spring-boot-gradle-plugin = { group = "org.springframework.boot", name = "spring-boot-gradle-plugin", version.ref = "springBoot" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }