[versions]
java = "21"
springBoot = "3.4.2"
springDependencyManagement = "1.1.7"
kotlin = "1.9.25"
lombok = "1.18.36"  
openapi = "7.10.0"
hibernateSpatial = "6.4.1.Final"
postgresql = "42.7.2"
opencsv = "5.9"
swaggerAnnotations = "2.2.20"
jacksonNullable = "0.2.6"
junitPlatform = "1.11.4"
jakartaAnnotation = "2.1.1"
jakartaValidation = "3.0.2"
jakartaServlet = "6.0.0"
springSession = "3.2.1"
commons-io = "2.11.0"
awaitility = "4.2.2"

[libraries]
# Spring boot Starters
spring-boot-starter-web = { group = "org.springframework.boot", name = "spring-boot-starter-web", version.ref = "springBoot" }
spring-boot-starter-data-jpa = {group = "org.springframework.boot", name = "spring-boot-starter-data-jpa", version.ref = "springBoot"}
spring-boot-starter-data-redis = {group ="org.springframework.boot", name ="spring-boot-starter-data-redis", version.ref = "springBoot"}
spring-boot-starter-validation = { group = "org.springframework.boot", name = "spring-boot-starter-validation", version.ref = "springBoot" }
spring-boot-starter-test = { group = "org.springframework.boot", name = "spring-boot-starter-test", version.ref = "springBoot" }
spring-boot-starter-security = {group = "org.springframework.boot", name = "spring-boot-starter-security", version.ref = "springBoot"}
spring-boot-starter-actuator = {group ="org.springframework.boot", name = "spring-boot-starter-actuator", version.ref = "springBoot"}

# 세션
spring-session-data-redis = { group = "org.springframework.session", name = "spring-session-data-redis", version.ref = "springSession" }

# 보안 테스트
spring-security-test = {group = "org.springframework.security", name = "spring-security-test"}

# DB 관련
h2 = { group = "com.h2database", name = "h2", version = "2.2.224" }
postgresql = { group = "org.postgresql", name = "postgresql", version.ref = "postgresql" }
hibernate-spatial = { group = "org.hibernate", name = "hibernate-spatial", version.ref = "hibernateSpatial" }

# 생산성 도구
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
junit-platform-launcher = {group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junitPlatform"}

# openapi
swagger-annotations = {group = "io.swagger.core.v3", name = "swagger-annotations", version.ref = "swaggerAnnotations"}
jackson-databind-nullable = { group = "org.openapitools", name = "jackson-databind-nullable", version.ref = "jacksonNullable" }

# Jakarta
jakarta-validation-api = { group = "jakarta.validation", name = "jakarta.validation-api", version.ref = "jakartaValidation"}
jakarta-annotation-api = { group = "jakarta.annotation", name = "jakarta.annotation-api", version.ref = "jakartaAnnotation"}
jakarta-servlet-api = { group = "jakarta.servlet", name = "jakarta.servlet-api", version.ref = "jakartaServlet"}

# 플러그인 구현채
spring-boot-gradle-plugin = { group = "org.springframework.boot", name = "spring-boot-gradle-plugin", version.ref = "springBoot" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

awaitility = { group = "org.awaitility", name = "awaitility", version.ref = "awaitility" }
opencsv = { group = "com.opencsv", name = "opencsv", version.ref = "opencsv" }
commons-io = { group = "commons-io", name = "commons-io", version.ref = "commons-io" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }
openapi-generator = {id = "org.openapi.generator", version.ref = "openapi"}
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

[bundles]
auth-api = ["swagger-annotations", "jakarta-validation-api", "jakarta-annotation-api", "jackson-databind-nullable"]
