#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: ideal
#    password:
#
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#
#  jpa:
#    defer-datasource-initialization: true # [핵심] 테이블 생성 후 data.sql 실행하도록 지연시킴
#
#    hibernate:
#      # 애플리케이션 로딩 시 @Entity를 보고 테이블 자동 생성
#      ddl-auto: create
#
#    properties:
#      hibernate:
#        format_sql: true # 로그에 찍히는 SQL 포맷팅
#
#    show-sql: true # 실행되는 SQL을 콘솔 로그에 출력
#
#  sql:
#    init:
#      mode: always