spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/seoulmap
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # 개발 초기에는 update, 운영 시에는 validate 또는 none 권장
    properties:
      hibernate:
        format_sql: true # 실행되는 SQL을 보기 좋게 정렬
        show_sql: true   # 실행되는 SQL을 콘솔에 출력